apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:64e4fe0bf7b3dd5e89689d750fb63d7e3111068f18a7ed8656265cb1775f3b68 # 0.11.0
  displayName: Argo CD Operators
  publisher: Argo CD Community